kvm:
  hostname: kvm
  ip: '14.88.0.2'
  ssh_port: 22
  localdomain: nekrohaven.lan
  interfaces:
  - iface_name: eth0
    role: LAN
    use_dhcp: false
    static_ip:
      ip: '14.88.0.2'
      netmask: '255.255.255.0'
  live_system:
    network_device: usb0
    ip: '14.88.0.3'
